Add missing quote leading to a puppet manifest parsing error
Error: Syntax error at 'ECISAL123D1'; expected '}' at /usr/share/puppet/modules/openiosds/manifests/conscience.pp:42

Fixes: d9a789bc78f1ee6148c47357e568ee67117250b0